# Generated by Django 5.2.7 on 2025-10-06 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(help_text="Name of the location (e.g., 'West Virginia University')", max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state_country', models.CharField(help_text='State (for US) or Country', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('description', models.TextField(help_text='Story or memory from this location')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='wedding/locations/')),
                ('date_visited', models.CharField(blank=True, help_text='When you visited (can be flexible format)', max_length=100)),
                ('significance', models.CharField(help_text='Why this place is special', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Order for chronological display')),
                ('is_active', models.BooleanField(default=True, help_text='Show this location on the map')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['order', 'date_visited'],
            },
        ),
        migrations.CreateModel(
            name='RSVP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('attendance', models.CharField(choices=[('yes', 'Joyfully Accept'), ('no', 'Regretfully Decline')], max_length=10)),
                ('number_of_guests', models.IntegerField(default=1, help_text='Total number attending (including yourself)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('guest_names', models.TextField(blank=True, help_text='Names of additional guests')),
                ('dietary_restrictions', models.TextField(blank=True)),
                ('song_request', models.CharField(blank=True, help_text="Song you'd love to hear at the reception", max_length=200)),
                ('message', models.TextField(blank=True, help_text='Any message for the couple')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSVP',
                'verbose_name_plural': 'RSVPs',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='WeddingPartyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('maid_of_honor', 'Maid of Honor'), ('best_man', 'Best Man'), ('bridesmaid', 'Bridesmaid'), ('groomsman', 'Groomsman'), ('flower_girl', 'Flower Girl'), ('ring_bearer', 'Ring Bearer')], max_length=50)),
                ('side', models.CharField(choices=[('bride', "Bride's Side"), ('groom', "Groom's Side")], max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='wedding/party/')),
                ('order', models.IntegerField(default=0, help_text='Display order in the gallery')),
                ('bio', models.TextField(blank=True, help_text='Optional bio or fun fact')),
                ('is_active', models.BooleanField(default=True, help_text='Include in wedding party display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wedding Party Member',
                'verbose_name_plural': 'Wedding Party Members',
                'ordering': ['side', 'order'],
            },
        ),
    ]
