# Generated by Django 5.2.7 on 2025-10-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='photo_base_name',
            field=models.CharField(blank=True, help_text="Base name for photos (e.g., 'morgantown' for morgantown_1.png, morgantown_2.png)", max_length=100),
        ),
    ]
