# Generated by Django 5.2.7 on 2025-10-07 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding', '0002_location_photo_base_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by_name', models.CharField(help_text='Name of person uploading', max_length=200)),
                ('phone', models.CharField(help_text='Phone number (to match with RSVP)', max_length=20)),
                ('photo_url', models.URLField(help_text='Cloudinary URL of uploaded photo')),
                ('caption', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Show on public gallery')),
            ],
            options={
                'verbose_name': 'Photo Upload',
                'verbose_name_plural': 'Photo Uploads',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='attendance',
            field=models.CharField(choices=[('yes', 'Accept'), ('no', 'Decline')], max_length=10),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='guest_names',
            field=models.TextField(blank=True, help_text='Names of additional guests (deprecated - use Guest model)'),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('use_primary_phone', models.BooleanField(default=True, help_text="Can we use the primary contact's phone number to reach this guest?")),
                ('phone', models.CharField(blank=True, help_text='Only if different from primary contact', max_length=20)),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='wedding.rsvp')),
            ],
            options={
                'verbose_name': 'Guest',
                'verbose_name_plural': 'Guests',
                'ordering': ['id'],
            },
        ),
    ]
